server:
  port: 8888

grpc:
  server:
    port: 50051
    security:
      enabled: false
    reflectionServiceEnabled: true

spring:
  datasource:
    url: jdbc:mariadb://49.50.166.122:3306/serverB_db
    username: ${DB_B_USERNAME}
    password: ${DB_B_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # (1) 스키마 생성
    show-sql: true # (2) SQL 쿼리 출력
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true # (3) SQL pretty print

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_KEY}
  token:
    access-expiration-time: 43200000    # 12시간
    refresh-expiration-time: 604800000   # 7일