server:
  port: 8888

grpc:
  port: 50051

spring:
  datasource:
    url: jdbc:mariadb://49.50.166.122:3306/serverB_db
    username: ${DB_B_USERNAME}
    password: ${DB_B_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

jwt:
  secret: ${JWT_KEY}
  token:
    access-expiration-time: 43200000    # 12시간
    refresh-expiration-time: 604800000   # 7일