spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create # (1) 스키마 생성
    show-sql: true # (2) SQL 쿼리 출력
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true # (3) SQL pretty print

  profiles:
    group:
      serverA: serverA
      serverB: serverB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver